version: '3.7'

services:
  postgres:
    container_name: postgres-topten
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgvolume-topten:/var/lib/postgresql/data
    env_file:
      - ./src/node-api/.env

  vue-frontend:
    container_name: vue-topten
    build: ./src/vue-frontend
    ports:
      - "8080:8080"
    
  node-api:
    container_name: node-topten
    build: ./src/node-api
    ports:
      - "3000:3000"

volumes:
  pgvolume-topten:
    external:
      name: pgvolume-topten