version: '3.7'

services:
  postgres:
    container_name: postgres-topten
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgvolume-topten:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  pgvolume-topten:
    external:
      name: pgvolume-topten