version: '3.7'

services:
  postgres:
    container_name: postgres-topten
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=somepassword
